#!/bin/sh
#updatehosts dispatcher script for NetworkManager
#

case "$2" in
    up)
        ip=$(/sbin/ifconfig ${1} | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}')
        internal=${ip//./-}
        if [ "${ip}" != "" ]
        then
                sed -i -e "/ADDED BY UPDATEHOSTS/d" /etc/hosts
                echo "${ip}     ip-${internal}  # ADDED BY UPDATEHOSTS" >> /etc/hosts
        fi
        ;;
    *)
        exit 0
        ;;
esac
